# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-16 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='cs_class',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='is_class',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
